Week5
IbrahimAtef22/JobHacker-System pull request #5
Opened 2023-05-06 01:02 UTC by IbrahimAtef22

2023-07-08 11:43 UTC, mohamedshaker9 requested changes

2023-07-08 11:43 UTC, mohamedshaker9 commented on Week5/week5tasks/src/InputMismatchTask1.java
try to solve it using try catch block and throw key word.

2023-07-08 11:43 UTC, mohamedshaker9 commented on Week5/week5tasks/src/CountWordsTask2.java
every time a read the file it will add 'Num Of Words = count' and the count will increase you can write it to new file not in the same file. 

aslo write clean code. 
extract the reading code to a new method. 
write good naming.

2023-07-08 11:43 UTC, mohamedshaker9 commented on Week5/week5tasks/src/CountWordsTask2.java
> +                if ((char)i == ' '){
why only count whitespaces?

2023-07-08 11:43 UTC, mohamedshaker9 commented on Week5/week5tasks/src/CalcSumAndAvgFromFile.java
> +            URLConnection urlConnection = urlObj.openConnection(); // creating an urlConnection object
You could extract it to a new method

2023-07-08 11:43 UTC, mohamedshaker9 commented on Week5/week5tasks/src/CalcSumAndAvgFromFile.java
> +                } catch (NumberFormatException | NullPointerException e) {
better use multiple catch block as these are very different exception and in real world you will handle them in different ways

2023-07-08 20:20 UTC, IbrahimAtef22 commented on Week5/week5tasks/src/InputMismatchTask1.java
I don't understand what throw key word refers to?
I will catch exception so why i should throw exception?

2023-07-14 12:56 UTC, mohamedshaker9 approved these changes

2023-07-16 18:07 UTC, merged